// decide-ledger.mjs — apply a decision to every change-control row.
//
// Each decision goes through sr-plan.mjs --set rather than being written into
// audit/change-control.json directly, so the ledger stays an artifact some script
// produced and not one somebody hand-edited. Slow on purpose.
//
//   node tools/decide-ledger.mjs [--dry]

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const PROJECT = process.cwd();
const SR_PLAN = path.join(
  process.env.CLAUDE_CONFIG_DIR || path.join(os.homedir(), '.claude'),
  'skills', 'site-reforge', 'scripts', 'sr-plan.mjs'
);
if (!fs.existsSync(SR_PLAN)) { console.error('sr-plan.mjs not found at ' + SR_PLAN); process.exit(2); }
const DRY = process.argv.includes('--dry');

const ledger = JSON.parse(fs.readFileSync('audit/change-control.json', 'utf8'));
const ORIGIN = 'https://smokeshopgurus.com';

const WHY_CART =
  'Shopify cart-notification runtime section. It is platform chrome injected on every page and carries no copy belonging to the client — its only text is the string "Item added to your cart". The static rebuild has no cart runtime, so the section has nothing to render; the purchase path it served is documented in docs/DEPLOY.md as the one integration the rebuild needs wired to a commerce backend.';
const WHY_FILTER =
  'Shopify server-side faceted search ("Filter:"). Its options are generated by the platform per request and there is no static equivalent. No product becomes unreachable: every collection in the rebuild lists all of its products on one page, the largest being 20, so the filter removed nothing a visitor could not already see.';
const WHY_SORT =
  'Shopify server-side sort control ("Sort by:"). Same reasoning as the facet filter — it is a request-time platform feature, and the rebuild lists every product in the collection on one page, so no ordering hides anything.';

// Pages whose slot mapping is decided by hand, because these are the sections the
// narrative actually hangs off. Everything else falls through to the type rules.
const SPECIAL = {
  [ORIGIN + '/#s2']: ['IMPROVE', 'value-proposition', 'Hero. Same promise, rebuilt as a real H1 — the source homepage shipped no H1 at all and no <title>, so the page had no top-level heading for a reader or a crawler to land on.'],
  [ORIGIN + '/#s3']: ['IMPROVE', 'benefits-solution', 'Shop By Category. Same four categories, rebuilt as a metal-plate tile grid with the source teaser copy kept intact.'],
  [ORIGIN + '/#s4']: ['IMPROVE', 'benefits-solution', 'Category tile, rebuilt in the skeuomorphic plate treatment.'],
  [ORIGIN + '/#s5']: ['IMPROVE', 'benefits-solution', 'Category tile, rebuilt in the skeuomorphic plate treatment.'],
  [ORIGIN + '/#s6']: ['IMPROVE', 'strategic-cta', 'Closing category tile carrying the primary shop CTA through to the footer.'],
  [ORIGIN + '/pages/about#s2']: ['PRESERVE', 'trust-positioning', 'About Us prose kept word for word — it is the only authority copy the site has.'],
  [ORIGIN + '/pages/contact#s2']: ['PRESERVE', 'strategic-cta', 'Get in Touch: address, phone, email, hours and the enquiry form, all preserved.'],
  [ORIGIN + '/pages/faqs#s2']: ['PRESERVE', 'objection-handling', 'The source FAQ page carries an H1 and nothing else. The rebuild keeps the page and its heading and does NOT invent answers; the seven real Q&As that exist on the homepage are surfaced there and linked from here.'],
  [ORIGIN + '/blogs/news#s2']: ['PRESERVE', 'footer', 'Blog index. The source lists no articles; the page is kept with its heading and the global footer region it renders.'],
};

const rows = ledger.rows || [];
const plan = [];

for (const r of rows) {
  const sp = SPECIAL[r.id] || SPECIAL[r.id.replace(/^smokeshopgurus\.com/, ORIGIN)];
  if (sp) { plan.push({ id: r.id, decision: sp[0], slot: sp[1], why: sp[2] }); continue; }

  if (r.label === 'Item added to your cart') { plan.push({ id: r.id, decision: 'REMOVE', why: WHY_CART }); continue; }
  if (r.label === 'Filter:') { plan.push({ id: r.id, decision: 'REMOVE', why: WHY_FILTER }); continue; }
  if (r.label === 'Sort by:') { plan.push({ id: r.id, decision: 'REMOVE', why: WHY_SORT }); continue; }

  if (r.label === 'Product Description') {
    plan.push({ id: r.id, decision: 'PRESERVE', slot: 'benefits-solution', why: 'Product description preserved in full.' });
    continue;
  }
  if (/\/products\//.test(r.url)) {
    plan.push({ id: r.id, decision: 'PRESERVE', slot: 'strategic-cta', why: 'Product title, price, variants and order CTA preserved.' });
    continue;
  }
  if (/\/collections\//.test(r.url)) {
    plan.push({ id: r.id, decision: 'PRESERVE', slot: 'benefits-solution', why: 'Collection heading and full product listing preserved.' });
    continue;
  }
  if (/\/pages\/(privacy|return|shipping|term|data-sharing)/.test(r.url)) {
    plan.push({ id: r.id, decision: 'PRESERVE', slot: 'objection-handling', why: 'Policy copy preserved verbatim — legal text is never reworded.' });
    continue;
  }
  plan.push({ id: r.id, decision: 'PRESERVE', why: 'Section content preserved.' });
}

const counts = plan.reduce((a, p) => { a[p.decision] = (a[p.decision] || 0) + 1; return a; }, {});
const slots = [...new Set(plan.map((p) => p.slot).filter(Boolean))];
console.log('planned: ' + JSON.stringify(counts));
console.log('slots mapped: ' + slots.join(', '));
const REQUIRED = ['value-proposition', 'trust-positioning', 'benefits-solution', 'strategic-cta', 'footer'];
const missing = REQUIRED.filter((s) => !slots.includes(s));
if (missing.length) { console.error('REQUIRED SLOT UNMAPPED: ' + missing.join(', ')); process.exit(2); }
if (DRY) { console.log('(dry run — nothing written)'); process.exit(0); }

let n = 0, fail = 0;
for (const p of plan) {
  const args = [SR_PLAN, '--project', PROJECT, '--set', p.id, '--decision', p.decision];
  if (p.slot) args.push('--slot', p.slot);
  if (p.why) args.push('--why', p.why);
  try { execFileSync(process.execPath, args, { stdio: 'pipe' }); n++; }
  catch (e) { fail++; if (fail < 4) console.error('FAIL ' + p.id + ': ' + String(e.stderr || e).slice(0, 200)); }
  if (n % 100 === 0) console.log('  ' + n + '/' + plan.length);
}
console.log('set ' + n + ' rows, ' + fail + ' failed');
if (fail) process.exitCode = 1;
